### ISSUE TITLE
How use callbacks and pass arguments to the child process

### ISSUE THREAD

**Issue by thebestclass** [reactphp/child-process#20]
I need to run a callback once the child process to stop to perform certain actions.

Also I need to pass arguments to the child process so that everything is run, I tried to pass the $conn object variable but it seems he does not accept it. How to resolve this?

What I have tried:

```
public function onOpen(ConnectionInterface $conn) {
    $callback = function () use ($conn) {
        echo "Hey, ".md5($conn->resourceId)."!\n";
    };

    $this->childProcess->stdin->write($conn, $callback);
```

He gave to understand what I'm trying to do? After passing the argument to the child process I want that callback is triggered and the user function md5 be used without blocking the process parents..

**Comment by WyriHaximus** [comment]
Take a look at https://github.com/jeremeamia/super_closure, you can serialize closures with it

**Comment by thebestclass** [comment]
But how? Did not quite understand.

There is to be straight in the `stdin->write()`?  @WyriHaximus

**Comment by WyriHaximus** [comment]
Yes you serialize it with the super closure serializer, write it into stdin on the parent process and read from stdin on the child process. (Make sure you can distinguish different messages coming in over stdin and out over stdout.)

**Comment by thebestclass** [comment]
@WyriHaximus Congratulations and thank you, you helped me, but I created a new question .. I updated the topic to match the current reality, you should probably have a solution, right?

**Comment by thebestclass** [comment]
@WyriHaximus  @cboden  Congratulations and thank you, you helped me, but I created a new question .. I updated the topic to match the current reality, you should probably have a solution, right?

**Comment by WyriHaximus** [comment]
Same as the serialized, send a message over stdin to the child and the response back over stdout. You're going to have to write something so they can communicate these messages properly. Wrote a package for that that might be interesting for you: https://github.com/WyriHaximus/reactphp-child-process-messenger

**Comment by thebestclass** [comment]
@WyriHaximus  Much more than interesting, amazing, just read the code.

Work with the resource type variables ($ conn)?

I tried to run the script but it seems that it did not work, I used the example folder, tried all the scripts it ...

**Comment by thebestclass** [comment]
@WyriHaximus  Much more than interesting, amazing,i just reading the code.

Work with the resource type variables ($conn)?

I tried to run the script but it seems that it did not work, I used the example folder, tried all the scripts it ... But the `echo's` of scripts didnt work, example:

    $messenger->rpc(MessageFactory::rpc('format', [
            'unixTime' => time(),
        ]))->then(function ($formattedTime) {
            echo $formattedTime['formattedTime'], PHP_EOL;
        });


are a bug?

**Comment by thebestclass** [comment]
@WyriHaximus pleasee help me, i depend on it for all my project

**Comment by WyriHaximus** [comment]
@thebestclass I will help you, it's just that attending conferences is exhausting

**Comment by clue** [comment]
Unfortunately this isn't really actionable currently, as it lacks details what particular feature is missing here.

The process exposes its STDIN and STDOUT streams which can be used to exchange arbitrary data.
If you're new to this concept, you may want to check out the react/stream component first.
The README now contains some hints for this, see also #26.

I hope this helps :+1:
