### ISSUE TITLE
proc_close can make PHP hang

### ISSUE THREAD

**Issue by uniquoooo** [reactphp/child-process#23]
I was testing some stuff out with my library that i'm working on and found that sometimes if you run `proc_close` before `proc_terminate` PHP hangs. Did a quick google search and came across this: https://bugs.php.net/bug.php?id=34794

When `close()` is run possibly terminate?

**Comment by clue** [comment]
Thanks for reporting @uniquoooo, can you give some steps to reproduce this? :+1: 

According to the bug report this should only trigger if you explicitly call `proc_close()` on the handle, which we provide no other access to than the `Process:close()` method. However, the documentation currently [advises against calling `Process:close()`](https://github.com/reactphp/child-process/blob/92b29374188e7bbfcfd5b9c9c1d68d7ec8358b30/src/Process.php#L121)?

**Comment by uniquoooo** [comment]
Yeah sorry, wasn't reading that `Process::close()` wasn't supposed to be called. If you want I can still post some testing code otherwise feel free to close the issue.

**Comment by clue** [comment]
I believe this has been resolved, so I'll close this for now. If you feel this problem persists, please report back and we can reopen this :+1:
