### ISSUE TITLE
Spawn child process and creatie server in it

### ISSUE THREAD

**Issue by demil** [reactphp/child-process#43]
Is it possible something similar to node cluster module

    `cluster = require('cluster');
    if (cluster.isMaster) {
    cluster.fork();
    cluster.on('fork', function(worker) {
    newPID = worker.process.pid;
    console.log(worker.process.pid);
    });
    cluster.on('exit', function(worker, code, signal) {
    cluster.fork();
    });
    } 
    if (cluster.isWorker) {
    //create server here and logic to restart process with process.exit(1); 
    }); 
    }`

When we have child and master process and we could restart server with simple endpoint /restart in which we are calling process.exit(1) - ( in node.js this works properly )

**Comment by clue** [comment]
Absolutely! :-) What you're asking for is way beyond the scope of this low level child-process component, but I don't see why it wouldn't be possible to build something like this on top of this component :+1: 

I'm not currently aware of any package that provides this out of the box, but if you happen to find or build one, make sure to let us know.

I hope this helps :+1:
