### ISSUE TITLE
Persistent SSH Child Process

### ISSUE THREAD

**Issue by Mrmrprofessional** [reactphp/child-process#48]
Is it possible to create a persistent connection to an IP over ssh and then be able to execute commands at will without having to ssh again?

**Comment by WyriHaximus** [comment]
You can call `ssh` but it won't be persistent out of the box. If the connection fails `ssh` will exit with an error. Have you looked at `mush`?

**Comment by Mrmrprofessional** [comment]
Is this what you mentioned: https://mosh.org?
All I really want to do is open several ssh connections (between raspberry pis) to be able to send commands at will without having to ssh every time. All the pis are on the same local network.

**Comment by WyriHaximus** [comment]
Yes I ment `mosh` sorry.

If you want to send messages between them why not use RabbitMQ with https://github.com/jakubkulhan/bunny ?

**Comment by clue** [comment]
It sounds like you may want to run multiple commands in a single shell session? In this case, perhaps this may help you: https://github.com/clue/php-shell-react/blob/master/examples/bash.php

```php
$shell = $launcher->createDeferredShell('ssh example.com');
$shell->execute('echo -n $USER')->then(function ($result) {
    var_dump('current user', $result);
});
$shell->execute('env | sort | head -n10')->then(function ($env) {
    var_dump('env', $env);
});
```

I hope this helps :+1:

**Comment by Mrmrprofessional** [comment]
What is the difference between the two? They seem to do relatively the same thing if I’m not mistaken. If I used the Child Process to establish a SSH connection, would it not persist until the connection is manually closed/on error? And then wouldn’t I be able to send commands through the connection? Or am I wrong? I didn’t see an example on the GitHub page that uses SSH. And if I used the PHP Shell React, would it be best to be used in conjunction with the child processes to prevent the rest of my app from being held up or does it already know to run as a child process? Thanks.

**Comment by clue** [comment]
You can of course also use `new Process('ssh example.com');` and send commands via STDIN and receive the command output via STDOUT. This is exactly what the above project does under the hood, plus it takes care of providing a sane interface to detect where the output of the first command ends and the output of the next command begins.
