### ISSUE TITLE
 What is the correct way to obtain data from a subprocess

### ISSUE THREAD

**Issue by Juanperezc** [reactphp/child-process#57]
I'm trying to get in the event on data to verify if a thread has a specific string but it happens that when there are many strings printing with echo in the console or after printing the first string does not check me well.

I do not know if it is the correct way to obtain data from a childprocess but this is the method understood in the examples

`  $this->childprocess->stdout->on('data', function ($chunk) {
            if ($chunk == "/exit"){
                echo $chunk; 
            }
        });`

also try it with trim ($ chunk)

at the beginning it works and the condition fulfills me but when the childprocess throws me a lot of data (many echo) it is lost and I do not know if it is the correct way to obtain data

**Comment by clue** [comment]
This is a very good (and common) question! It looks like you want to consume the output of said program in a line-based fashion. The STDOUT stream does not care about the concept of "lines", it merely reports all the data it sees.

This means that you will have to implement some simple buffering and extract on line breaks like this (untested pseudo code, but I hope you get the idea):

```php
$buffer = '';
$stream->on('data', function ($chunk) use (&$buffer) {
    $buffer.= $chunk;
    while (($pos = strpos($buffer, "\n")) !== false) {
        $line = substr($buffer, 0, $pos);
        $buffer = substr($buffer, $pos + 1);

        // do something with $line
    }
});
```

I hope this helps :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
