### ISSUE TITLE
PHPUnit Code Coverage for runned process

### ISSUE THREAD

**Issue by Kolesar** [reactphp/child-process#61]
Is it possible somehow to run PHPUnit Code Coverage on the process which is run with `Process`? In my application, I run a couple of PHP sub-processes of my code, but I want to check Code Coverage on that.

**Comment by clue** [comment]
@Kolesar Welcome to ReactPHP and thanks for you excellent question! Unfortunately this is somewhat out of scope of this project, so I'm not sure this is the right place for this question.

The same question applies to running any external process with PHP, be it a `exec()` call or accessing things via HTTP etc., so perhaps StackOverflow etc. could help here? :+1: If anybody has an answer for this, feel free to respond to this ticket!

Other than that, I believe this has been answered, so I'm closing this for now.
