### ISSUE TITLE
is it possible to debug a child process?

### ISSUE THREAD

**Issue by nivpenso** [reactphp/child-process#86]

**Comment by clue** [comment]
> is it possible to debug a child process?

Yes.

---

Welcome to @ReactPHP! :wave: If you can give us a more precise question, we may be able to give a more helpful answer :+1: What are you trying to achieve exactly?

**Comment by nivpenso** [comment]
Hi @clue apologies for posting the issue with no description that was a mistake, can you please re-open it again unless the answer is the same. If so, I would kindly request to get more assistance to achieve that :)

Thanks
